<?php

  use Drupal\Core\Form\FormState;
  use Drupal\Core\Database\Database;
  use Drupal\Core\Database\Connection;
  use Drupal\Component\DependencyInjection\Container;
  use Drupal\synchron\Schema\SynchronService;

  function synchron_form_alter(&$form, FormState $formstate) {

    // Get main synchron services
    $synchronService = \Drupal::service('synchron_service');

    // Get name off from and to databases
    $fromDatabase = $synchronService->getDefaultConnectionOptions()['database'];
    $toDatabase = $fromDatabase === 'ixarm' ? 'ixarm_achats' : 'ixarm';

    var_dump($fromDatabase);
    var_dump($toDatabase);
    die();

    // Set database connection to ixarm
    $synchronService->setConnectionDatabase('ixarm');
    print_r(getEntity());
    $loadNode = loadNode(11257);
    var_dump($loadNode->toArray());

    print_r('<--------------------------!!!!!!!-------------------------->');

    // Set database connection to ixarm achats
    $synchronService->setConnectionDatabase('ixarm_achats');
    print_r(getEntity());
    $loadNode = loadNode(11257);
    var_dump($loadNode->toArray());

    die();
  }

  function getEntity() {
    // Get entity
    $query = \Drupal::entityQuery('node');
    $query->condition('type', 'article');
    $entity_ids = $query->execute();
    return $entity_ids;
  }



  function loadNode($nid) {
    \Drupal::entityManager()->getStorage('node')->resetCache(array($nid));
    return \Drupal\node\Entity\Node::load($nid);
  }

  function synchronFromTo($entity, $fromDatabaseName, $toDatabaseName) {

  }
